[package]
name = "gvdb-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glib = "0.15.10"
glib-sys = "0.15.10"
once_cell = "1.10.0"
deku = "0.13.0"
