name: Cargo Build & Test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose --all-features
      - name: Clippy
        run: cargo clippy --verbose --all-features -- -D warnings
      - name: Run tests
        run: cargo test --verbose --all-features
      - name: Compile documentation
        run: cargo doc --verbose --no-deps --all-features
