[package]
name = "gvdb"
version = "0.4.2"
edition = "2021"
description = "Read and write GLib GVariant database files"
repository = "https://github.com/felinira/gvdb-rs"
license = "MIT"
keywords = [ "gvdb", "glib", "gresource", "compile-resources" ]
categories = [ "gui", "data-structures", "encoding" ]
exclude = [ "test/c" ]
rust-version = "1.65"

[package.metadata.docs.rs]
all-features = true

[dependencies]
safe-transmute = "0.11"
walkdir = "2.3"
memmap2 = "0.7"
lazy_static = "1.4"

glib = { version = "0.17", optional = true }
quick-xml = { version = "0.29", optional = true, features = ["serialize"] }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = [ "derive" ] }
flate2 = { version = "1.0", optional = true }
zvariant = { version = "3.2", default-features = false, features = ["gvariant"] }
byteorder = "1.4"

[dev-dependencies]
pretty_assertions = "1.2"
matches = "0.1"
serde_json = "1.0"
glib = "0.17"

# Use zlib for binary compatibility in tests
flate2 = { version = "1.0", features = [ "zlib" ] }

[features]
gresource = ["dep:quick-xml", "dep:serde_json", "dep:flate2"]
glib = ["dep:glib"]
default = []
