name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust:
          - "1.85" # MSRV
          - "stable"
        target:
          - "x86_64-unknown-linux-gnu"
          - "x86_64-pc-windows-gnu"
          - "x86_64-apple-darwin"
        include:
          - target: "x86_64-unknown-linux-gnu"
            features: "--all-features"
          - target: "x86_64-pc-windows-gnu"
            features: "--no-default-features --features=mmap,gresource"
          - target: "x86_64-apple-darwin"
            features: "--no-default-features --features=mmap,gresource"
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev

      - name: Install rust ${{ matrix.rust }}
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
          targets: ${{ matrix.target }}
      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-test-dotcargo-${{ matrix.rust }}-{{ matrix.target }}-${{ hashFiles('**/Cargo.toml') }}

      - name: Install cargo-all-features
        if: ${{ matrix.x86_64-unknown-linux-gnu }} == "x86_64-unknown-linux-gnu"
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cargo-all-features
      - name: Build
        run: cargo build --verbose ${{ matrix.features }} --target ${{ matrix.target }}
      - name: Clippy
        if: ${{ matrix.rust != 'stable' }}
        run: cargo clippy --verbose ${{ matrix.features }} --target ${{ matrix.target }} -- -D warnings
      - name: Clippy Tests
        if: ${{ matrix.rust != 'stable' && matrix.target == 'x86_64-unknown-linux-gnu' }}
        run: cargo clippy --tests --verbose ${{ matrix.features }} --target ${{ matrix.target }} -- -D warnings
      - name: Run tests
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }}
        run: cargo test-all-features --verbose --target ${{ matrix.target }}
      - name: Compile documentation
        run: cargo doc --verbose --no-deps ${{ matrix.features }} --target ${{ matrix.target }}

  big_endian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-s390x-cargo-${{ hashFiles('**/Cargo.toml') }}

      - uses: uraimo/run-on-arch-action@v3
        name: Build and test on s390x
        id: runcmd
        with:
          arch: s390x
          distro: ubuntu_devel
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "${HOME}/.cargo:/root/.cargo"
          install: |
            apt-get update && apt-get install -y libglib2.0-dev rustup build-essential
          run: |
            rustup install stable
            cargo test --all-features --verbose
            chmod -R a+r target
