name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust beta
        run: rustup install beta; rustup component add clippy --toolchain beta
      - name: Build
        run: cargo +beta build --verbose --all-features
      - name: Clippy
        run: cargo +beta clippy --verbose --all-features -- -D warnings
      - name: Run tests
        run: cargo +beta test --verbose --all-features
      - name: Compile documentation
        run: cargo +beta doc --verbose --no-deps --all-features
