name: REUSE Compliance Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libglib2.0-dev
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v2
